# -*- coding: utf-8 -*-
"""Trainnnnn_hak12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qau9vxnMGnlsBHCv3IuRq14HVD2lTG_N
"""

# ================================
# 1. تثبيت المكتبات (مرة وحدة)
# ================================
!apt-get install tesseract-ocr -y
!apt-get install tesseract-ocr-ara -y
!pip install pytesseract opencv-python gTTS openai

# ================================
# 2. الاستيراد والإعداد
# ================================
import base64
import cv2
import numpy as np
import pytesseract
from openai import OpenAI
from IPython.display import Audio, display, Javascript
from google.colab.output import eval_js

client = OpenAI(
    api_key="sk-0QsnUe6YOHhAQWg1wWMuCw",  # 🔑 حطي مفتاحك هنا
    base_url="https://elmodels.ngrok.app/v1"
)

# ================================
# 3. التقاط صورة من الكاميرا
# ================================
def take_photo():
    js = Javascript('''
        async function takePhoto() {
            const div = document.createElement('div');
            const video = document.createElement('video');
            const button = document.createElement('button');

            button.textContent = '📷 التقاط صورة للتحليل';
            button.style.padding = '10px';
            button.style.fontSize = '18px';

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            document.body.appendChild(div);
            div.appendChild(video);
            div.appendChild(button);

            video.srcObject = stream;
            await video.play();

            await new Promise((resolve) => button.onclick = resolve);

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;

            canvas.getContext('2d').drawImage(video, 0, 0);
            stream.getTracks().forEach(track => track.stop());
            div.remove();

            return canvas.toDataURL('image/jpeg');
        }
    ''')
    display(js)
    data = eval_js('takePhoto()')
    return data

print("🚀 النظام جاهز.. افتح الكاميرا")

# ================================
# 4. التنفيذ الرئيسي
# ================================
try:
    # التقاط الصورة
    raw_image = take_photo()
    image_base64 = raw_image.split(',')[1]

    # تحويل الصورة
    nparr = np.frombuffer(base64.b64decode(image_base64), np.uint8)
    img_cv2 = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    print("🧠 جاري التحليل...")

    # ================================
    # 5. تحليل الصورة (AI)
    # ================================
    response = client.chat.completions.create(
        model="nuha-2.0",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "اشرح الصورة لذوي الإعاقة البصرية وحدد مستوى الحالة: (آمن / تنبيه / خطر / غير واضح)"
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{image_base64}"}
                    }
                ]
            }
        ]
    )

    analysis = response.choices[0].message.content

    # ================================
    # 6. OCR استخراج النص
    # ================================
    extracted_text = pytesseract.image_to_string(img_cv2, lang='ara+eng').strip()

    # ================================
    # 7. دمج النتائج
    # ================================
    final_report = f"{analysis}"
    if extracted_text:
        final_report += f"\n📄 النص الموجود: {extracted_text}"

    print("-" * 40)
    print("📄 التقرير:\n", final_report)

    # ================================
    # 8. تحليل الحالة (تنبيه ذكي)
    # ================================
    check_text = final_report.lower()

    danger_keywords = ["خطر", "حادث", "اصابة", "danger", "warning"]
    important_keywords = ["تنبيه", "انتبه", "مهم", "notice"]
    unclear_keywords = ["غير واضح", "غير واضحه", "unclear", "blur"]
    liability_keywords = ["غير مسؤول", "لا نتحمل", "disclaimer"]

    alert_message = ""
    vibration_pattern = [50]

    if any(word in check_text for word in danger_keywords):
        print("🚨 اهتزاز قوي: خطر!")
        alert_message = "🚨 تحذير! تحذير! يوجد خطر، انتبه فوراً!"
        vibration_pattern = [300, 100, 300, 100, 500]

    elif any(word in check_text for word in important_keywords + liability_keywords):
        print("⚠️ اهتزاز متوسط: تنبيه")
        alert_message = "⚠️ تنبيه! يوجد أمر مهم يجب الانتباه له."
        vibration_pattern = [200, 100, 200]

    elif any(word in check_text for word in unclear_keywords):
        print("📳 اهتزاز خفيف: الصورة غير واضحة")
        alert_message = "📳 ملاحظة: الصورة غير واضحة، حاول مرة أخرى."
        vibration_pattern = [100]

    else:
        print("✅ الوضع آمن")
        alert_message = "✅ الوضع آمن."

    # ================================
    # 9. دمج التنبيه مع الصوت
    # ================================
    final_voice_text = alert_message + "\n" + final_report

    # ================================
    # 10. تحويل إلى صوت
    # ================================
    tts_response = client.audio.speech.create(
        model="elm-tts",
        voice="default",
        input=final_voice_text
    )

    audio_file = "output.mp3"
    with open(audio_file, "wb") as f:
        f.write(tts_response.content)

    display(Audio(audio_file, autoplay=True))

    # ================================
    # 11. تنفيذ الاهتزاز
    # ================================
    display(Javascript(f"navigator.vibrate({vibration_pattern});"))

except Exception as e:
    print(f"❌ خطأ: {e}")